-- absolute_term PostgreSQL schema
-- 库名: absolute_term_db

BEGIN;

CREATE TABLE IF NOT EXISTS user_tb (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        text NOT NULL UNIQUE,
    password_hash   text NOT NULL,
    cookie          text NOT NULL DEFAULT '',
    enable          text NOT NULL DEFAULT 'T',
    balance         numeric(12, 2) NOT NULL DEFAULT 0,
    auto_scan       boolean NOT NULL DEFAULT false,
    phone           text NOT NULL DEFAULT '',
    last_login_ip   text NOT NULL DEFAULT '',
    last_login_city text NOT NULL DEFAULT '',
    last_login_at   timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE user_tb IS '扫描系统用户；cookie 存该用户淘宝 Cookie（服务器侧备用）';
COMMENT ON COLUMN user_tb.password_hash IS 'sha256(salt + password)，salt 见 config.ini [db] password_salt';
COMMENT ON COLUMN user_tb.cookie IS '淘宝 Cookie 原文；本机抓取仍优先用客户端本地 Cookie';
COMMENT ON COLUMN user_tb.balance IS '用户余额（预留计费）';
COMMENT ON COLUMN user_tb.auto_scan IS '是否已永久开通自动扫描（扣费后为 true）';
COMMENT ON COLUMN user_tb.phone IS '手机号，可选，仅用于找回密码/用户名';
COMMENT ON COLUMN user_tb.last_login_ip IS '最近一次登录的 IP（取自 X-Forwarded-For/X-Real-IP）';
COMMENT ON COLUMN user_tb.last_login_city IS '最近一次登录 IP 归属城市（[geo] 接口查得，查不到为空）';
COMMENT ON COLUMN user_tb.last_login_at IS '最近一次登录时间；从未登录为 NULL';

-- 店铺库（fix.md：我的店铺库）
CREATE TABLE IF NOT EXISTS shop_tb (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer NOT NULL REFERENCES user_tb(id) ON DELETE CASCADE,
    shop_name       text NOT NULL DEFAULT '',
    shop_link       text NOT NULL DEFAULT '',
    goods_sum       integer NOT NULL DEFAULT 0,
    bad_goods_sum   integer NOT NULL DEFAULT 0,
    -- 抓取用淘宝侧 ID（页面不直接展示）
    tb_shop_id      text NOT NULL DEFAULT '',
    seller_id       text NOT NULL DEFAULT '',
    item_ids        jsonb NOT NULL DEFAULT '[]'::jsonb,
    item_titles     jsonb NOT NULL DEFAULT '{}'::jsonb,
    status          text NOT NULL DEFAULT 'ready',
    last_error      text NOT NULL DEFAULT '',
    source_md       text NOT NULL DEFAULT '',
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE shop_tb IS '我的店铺库';
COMMENT ON COLUMN shop_tb.user_id IS '外键 → user_tb.id';
COMMENT ON COLUMN shop_tb.shop_name IS '店铺名字';
COMMENT ON COLUMN shop_tb.shop_link IS '店铺/入口商品链接';
COMMENT ON COLUMN shop_tb.goods_sum IS '总商品数';
COMMENT ON COLUMN shop_tb.bad_goods_sum IS '有问题商品总数';
COMMENT ON COLUMN shop_tb.source_md IS '客户端店铺源文件全文（一店一 md）；换机下载、重扫覆盖';

CREATE UNIQUE INDEX IF NOT EXISTS uq_shop_tb_user_tbshop
    ON shop_tb(user_id, tb_shop_id);
CREATE INDEX IF NOT EXISTS idx_shop_tb_user ON shop_tb(user_id);
CREATE INDEX IF NOT EXISTS idx_shop_tb_updated ON shop_tb(updated_at DESC);

-- 商品问题明细（只记录有问题的商品；没问题的不入库）
CREATE TABLE IF NOT EXISTS goods_tb (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id         integer NOT NULL REFERENCES shop_tb(id) ON DELETE CASCADE,
    goods_name      text NOT NULL DEFAULT '',
    goods_link      text NOT NULL DEFAULT '',
    problem         text NOT NULL DEFAULT '',
    tb_item_id      text NOT NULL DEFAULT '',
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE goods_tb IS '店铺下「有问题」商品明细（markdown）；无问题商品不入库';
COMMENT ON COLUMN goods_tb.shop_id IS '外键 → shop_tb.id';
COMMENT ON COLUMN goods_tb.goods_name IS '商品名';
COMMENT ON COLUMN goods_tb.goods_link IS '商品链接';
COMMENT ON COLUMN goods_tb.problem IS '问题说明，md 格式：主图/详情；非空才会写入本表';

CREATE UNIQUE INDEX IF NOT EXISTS uq_goods_tb_shop_item
    ON goods_tb(shop_id, tb_item_id);
CREATE INDEX IF NOT EXISTS idx_goods_tb_shop ON goods_tb(shop_id);

-- 平台自有店铺资料库（从各客户端汇聚，非用户私有「我的店铺库」）
CREATE TABLE IF NOT EXISTS shop_uniq_tb (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name       text NOT NULL DEFAULT '',
    shop_link       text NOT NULL DEFAULT '',
    shop_content    text NOT NULL DEFAULT '',
    content_hash    text NOT NULL DEFAULT '',
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE shop_uniq_tb IS '收录各店铺全文资料（客户端扫描汇聚），平台自有数据';
COMMENT ON COLUMN shop_uniq_tb.shop_name IS '店铺名字';
COMMENT ON COLUMN shop_uniq_tb.shop_link IS '店铺链接';
COMMENT ON COLUMN shop_uniq_tb.shop_content IS '店铺文字 markdown，由客户端上传汇聚';
COMMENT ON COLUMN shop_uniq_tb.content_hash IS 'shop_content 的 sha256，用于差异判断';

CREATE UNIQUE INDEX IF NOT EXISTS uq_shop_uniq_tb_link
    ON shop_uniq_tb(shop_link) WHERE shop_link <> '';
CREATE INDEX IF NOT EXISTS idx_shop_uniq_tb_name ON shop_uniq_tb(shop_name);
CREATE INDEX IF NOT EXISTS idx_shop_uniq_tb_updated ON shop_uniq_tb(updated_at DESC);

-- 待检查店铺（自动/半自动采链入队；扫完硬删除）
CREATE TABLE IF NOT EXISTS scan_shop_tb (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer NOT NULL REFERENCES user_tb(id) ON DELETE CASCADE,
    shop_name       text NOT NULL DEFAULT '',
    shop_link       text NOT NULL DEFAULT '',
    tb_shop_id      text NOT NULL DEFAULT '',
    seller_id       text NOT NULL DEFAULT '',
    item_id         text NOT NULL DEFAULT '',
    created_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE scan_shop_tb IS '待检查店铺队列；扫完后硬删除，不软删';
COMMENT ON COLUMN scan_shop_tb.shop_name IS '店铺名字';
COMMENT ON COLUMN scan_shop_tb.shop_link IS '入口商品链接';
COMMENT ON COLUMN scan_shop_tb.tb_shop_id IS '淘宝 shopId，用于与 shop_tb 去重';
COMMENT ON COLUMN scan_shop_tb.seller_id IS '淘宝卖家 userId，扫描全店用';
COMMENT ON COLUMN scan_shop_tb.item_id IS '种子商品 id';

CREATE UNIQUE INDEX IF NOT EXISTS uq_scan_shop_tb_user_tbshop
    ON scan_shop_tb(user_id, tb_shop_id) WHERE tb_shop_id <> '';
CREATE INDEX IF NOT EXISTS idx_scan_shop_tb_user ON scan_shop_tb(user_id);

-- 短信验证码（找回密码/用户名、绑定手机）
CREATE TABLE IF NOT EXISTS sms_code_tb (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone           text NOT NULL,
    purpose         text NOT NULL,
    code            text NOT NULL,
    expires_at      timestamptz NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE sms_code_tb IS '短信验证码；校验成功后硬删除';
CREATE INDEX IF NOT EXISTS idx_sms_code_tb_phone_purpose ON sms_code_tb(phone, purpose);

-- 充值订单（微信/支付宝）；paid 时幂等入账 user_tb.balance
CREATE TABLE IF NOT EXISTS pay_order_tb (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer NOT NULL REFERENCES user_tb(id) ON DELETE CASCADE,
    order_no        text NOT NULL UNIQUE,
    channel         text NOT NULL,
    amount_cents    integer NOT NULL,
    status          text NOT NULL DEFAULT 'pending',
    trade_no        text NOT NULL DEFAULT '',
    created_at      timestamptz NOT NULL DEFAULT now(),
    paid_at         timestamptz
);

COMMENT ON TABLE pay_order_tb IS '充值订单；channel=wechat|alipay；status=pending|paid|closed';
COMMENT ON COLUMN pay_order_tb.order_no IS '商户订单号（全局唯一，传给支付网关）';
COMMENT ON COLUMN pay_order_tb.channel IS '支付通道：wechat|alipay';
COMMENT ON COLUMN pay_order_tb.amount_cents IS '金额（分）';
COMMENT ON COLUMN pay_order_tb.status IS 'pending 待支付 / paid 已入账 / closed 关闭';
COMMENT ON COLUMN pay_order_tb.trade_no IS '支付网关交易号（回调/查单回填）';
CREATE INDEX IF NOT EXISTS idx_pay_order_tb_user ON pay_order_tb(user_id);
CREATE INDEX IF NOT EXISTS idx_pay_order_tb_status ON pay_order_tb(status);

-- 用户意见/建议（客户端「提意见」提交；管理员「意见库」查看/筛选/删除）
CREATE TABLE IF NOT EXISTS suggestion_tb (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment         text NOT NULL,
    user_id         integer NOT NULL REFERENCES user_tb(id) ON DELETE CASCADE,
    date            timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE suggestion_tb IS '用户意见/建议；客户端提交，管理员意见库管理（人工删/LLM 筛选删无意义）';
COMMENT ON COLUMN suggestion_tb.comment IS '意见正文';
COMMENT ON COLUMN suggestion_tb.user_id IS '外键 → user_tb.id（谁提的）';
COMMENT ON COLUMN suggestion_tb.date IS '提交时间';
CREATE INDEX IF NOT EXISTS idx_suggestion_tb_date ON suggestion_tb(date DESC);

-- 登录会话（落库，服务重启不丢）
-- channel=client：客户端桌面端，expires_at 为 NULL，只在主动退出时删
-- channel=web：网页，expires_at 按 [auth] session_ttl_seconds
CREATE TABLE IF NOT EXISTS session_tb (
    token           text PRIMARY KEY,
    user_id         integer NOT NULL REFERENCES user_tb(id) ON DELETE CASCADE,
    channel         text NOT NULL DEFAULT 'web',
    expires_at      timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    last_seen_at    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE session_tb IS '登录 Bearer token；client 不过期除非退出；web 有 TTL；重启服务不丢';
COMMENT ON COLUMN session_tb.token IS 'Bearer token 原文';
COMMENT ON COLUMN session_tb.channel IS 'client=桌面客户端；web=网页';
COMMENT ON COLUMN session_tb.expires_at IS '过期时间；client 为 NULL 表示不过期';
CREATE INDEX IF NOT EXISTS idx_session_tb_user ON session_tb(user_id);
CREATE INDEX IF NOT EXISTS idx_session_tb_expires ON session_tb(expires_at);

COMMIT;
